<?php
	$brand = $this->getBrand();
	if(!$brand) return;
?>
<div class="brand">
    <h3 class="title"><?php echo __('Brand') ?></h3>
	<a href="<?php echo $this->getUrlBrand($brand) ?>">
		<span><?php echo __($brand->getLabel()) ?></span>
		<?php if($brand->getData('image')) : ?>
		<img class="brand img-responsive" src="<?php /* @escapeNotVerified */ echo $this->getImage($brand)?>" alt="<?php /* @escapeNotVerified */ echo __($brand->getTitle()) ?>" title="<?php /* @escapeNotVerified */ echo __($brand->getTitle()) ?>" />
		<?php endif ?>
	</a>
</div>
